### ISSUE TITLE
Problem updating: "Update failed: server responded with code 404."

### ISSUE THREAD

**Issue by synthead** [pyxelr/Dark_Google_Calendar#10]
When clicking the update icon in Stylus, the icon goes red, and the tooltip for it looks like this:

![image](https://user-images.githubusercontent.com/820984/97032498-cb58f280-1516-11eb-96ff-be3a9071783f.png)

**Comment by synthead** [comment]
Ah, looks like this file was removed in https://github.com/pyxelr/Dark_Google_Calendar/commit/e99e510a1c59da404eeb9f276b39f3af7fd12508.  I uninstalled and reinstalled the style, and things are working great.

**Comment by synthead** [comment]
I'm going to close this issue because I found a viable workaround :+1:

**Comment by pyxelr** [comment]
Exactly, the error is caused by the mentioned commit and resolved by reinstalling the style. That time, I was fixing the SemVer versioning issue, and in the result, I changed the file name for the `.user.css` file. This is why Stylus responses with 404 due to an outdated `@updateURL` parameter.

I am happy to see that you resolved it on your own. :)
