### ISSUE TITLE
Event text is dark on dark when viewing in 'custom view' after latest commit

### ISSUE THREAD

**Issue by mcavag** [pyxelr/Dark_Google_Calendar#22]
I have my custom view set to 4 weeks, and text is now dark on dark (i.e. not readable) after the latest commit.

**Comment by pyxelr** [comment]
@mcavag: Could you provide a screenshot?

I am not observing any change in the custom view (4 weeks) on the [Google Calendar site](https://calendar.google.com/calendar/u/0/r/customweek), with or without the latest commit (4d6ed7f).

Here is what I am seeing:

![2023-10-19_17-52-12](https://github.com/pyxelr/dark-google-calendar/assets/30161753/b24c393e-af73-4110-aeb1-df17e63cd4a6)

Maybe reinstalling the theme or trying it in a different browser would help on your side.

**Comment by mcavag** [comment]
Here's what I'm seeing. It could very well just be my machine. I've cleared cache, restarted Chrome, reinstalled the script, etc. I don't have any other styles installed.

Chrome version 118.0.5993.88 on MacOS Ventura.

<img width="425" alt="Screenshot 2023-10-19 at 9 05 23 AM" src="https://github.com/pyxelr/dark-google-calendar/assets/9151426/831abec3-af97-4b06-8a5a-5cacaea9cf28">

**Comment by pyxelr** [comment]
Ok, I have been able to replicate the issue. Perhaps, you have modified the applied font colour during the installation.

In order to resolve it, you would need to follow these steps:

1. Hit the "Stylus" extension icon (if you are using other browser extension, the steps may be a bit different).
2. Click the "gear" icon next to "Dark Google Calendar".

![image](https://github.com/pyxelr/dark-google-calendar/assets/30161753/1c770205-2f3e-479a-9714-356712e3c03f)

3. Press the "Reset" button, or modify the colours as you like.
4. You should observe the following:

![image](https://github.com/pyxelr/dark-google-calendar/assets/30161753/e4a07f3b-a9c7-40cd-b420-4f258f0d9973)

Hopefully, it helps.

**Comment by mcavag** [comment]
Thanks for this. I switched from Stylish to Stylus, and that fixed the problem.

**Comment by pyxelr** [comment]
No problem, I have also resolved the issue for Stylish, although, the community strongly recommends Stylus.

I did not notice that the [userstyles.org](https://userstyles.org/styles/143026/dark-google-calendar-2020) website uses slightly different CSS syntax; therefore, it entirely ignored the variables I have left in the CSS code for the custom font color.
